<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmaChain.Domain\PharmaChain.Domain.csproj" />
    <ProjectReference Include="..\PharmaChain.Application\PharmaChain.Application.csproj" />
    <ProjectReference Include="..\PharmaChain.Infrastructure\PharmaChain.Infrastructure.csproj" />
  </ItemGroup>

</Project>
